### ISSUE TITLE
Title bar does not change when switching app windows

### ISSUE THREAD

**Issue by sirfz** [deadalnix/pixel-saver#45] opened 2015-11-07 20:04 UTC
The title bar changes normally when switching windows between different apps, but fails to do so when switching windows of the same app (for example multiple Terminal windows, switch using ``alt+` ``).

I've replaced this line (#193) in `app_menu.js`:
```javascript
focusCallbackID = Shell.WindowTracker.get_default().connect('notify::focus-app', onFocusChange);
```
with
```javascript
focusCallbackID = global.display.connect('notify::focus-window', onFocusChange);
```
This seems to have fixed this issue but I'm not sure if it affects any other functionality or whether it's the best way to do it.

**Comment by deadalnix** [comment] 2015-12-14 07:05
Is that a duplicate of #48 ?

**Comment by sirfz** [comment] 2016-04-29 13:15
I have my fix applied, which solves the problem reported here but it doesn't solve #48 (just tested it). I usually use <kbd>Super</kbd>+<kbd>Up</kbd> to maximize and it properly updates the title bar.

**Comment by deadalnix** [comment] 2016-05-01 06:40
Ok so I have no idea what this change does. (I'm completely cargo culting with this extension, if that was not clear). What is the difference between Shell.WindowTracker.get_default() and global.display ?

Also, what version fo the shell have you tested on ?

**Comment by marcohu** [comment] 2016-05-01 09:57
I'm using this fix on 3.14. It should work with later versions as well, I would assume.

The difference between Shell.WindowTracker and global.display is not important.
https://github.com/GNOME/gnome-shell/blob/master/src/shell-window-tracker.c
https://github.com/GNOME/mutter/blob/master/src/core/display.c

The important thing is that with the former you receive notification only when an application is switched. With the latter you can receive notification when the application window is switched which is necessary here.

**Comment by sirfz** [comment] 2016-05-01 16:42
I'm using it on 3.18, I don't know the difference to be honest (zero gnome extensions coding experience). I think I got it after looking at https://github.com/emerinohdz/status-title-bar which was properly displaying the title for me in 3.16.

@marcohu's explanation makes perfect sense tho!

**Comment by marcohu** [comment] 2016-05-01 17:07
These are just entirely different events. We definitely need window focus notification, otherwise the title is not always updated.

It works fine, but I've stumbled over a side effect (because of https://github.com/deadalnix/pixel-saver/commit/f9e109898398c960002d4cae1d829537e6e83b53#diff-77b7f4dcbed5082f9338a12ed5d7e41c): if an application has several windows opened and one window description cannot be read, it might be that the X id cannot be guessed. Well, but Pixel Saver currently decides not to. I haven't looked into this in detail, but it's no biggie.

**Comment by deadalnix** [comment] 2016-05-01 22:04
Ok this looks legit. Making a patch.

**Comment by deadalnix** [comment] 2016-05-01 22:08
Pushed, closing.

**Closed by deadalnix** 2016-05-01 22:08 UTC
