### ISSUE TITLE
Not working with gnome-terminal 3.22

### ISSUE THREAD

**Issue by cxnam** [deadalnix/pixel-saver#93] opened 2016-10-18 02:43 UTC
Hello,
I use gnome-terminal 3.22 on fedora 25 and not working with pixel-saver 1.9
![screenshot from 2016-10-18 09-39-19](https://cloud.githubusercontent.com/assets/5145416/19462493/41f7b400-9517-11e6-852d-73d969a21d6b.png)

**Comment by mrPjer** [comment] 2016-10-20 12:44
I think this is related to #32

**Comment by cxnam** [comment] 2016-10-20 14:59
@mrPjer oh, tks for reply

**Comment by deadalnix** [comment] 2016-11-18 10:12
Ok closing as this is duplicated. I'm aware this isn't working with wayland as it should. I'm trying to figure out a fix, but at this stage, I'm not even sure there is a way :/

**Comment by cxnam** [comment] 2016-11-21 07:32
@deadalnix tks, i switch to Xorg and work fine.
![screenshot from 2016-11-21 14-31-44](https://cloud.githubusercontent.com/assets/5145416/20474082/4f074ad4-aff7-11e6-9355-edc8bbc8ed60.png)

**Comment by deadalnix** [comment] 2016-11-21 07:37
So I reached to the gnome team for the wayland problem and its not sure
there is a solution so far :/

**Comment by jhasse** [comment] 2016-11-24 19:44
This is a duplicate of #32, let's discuss this there :)

**Closed** 2016-11-29 01:53 UTC
